version: "3.8"

services:
  web:
    image: mnmonherdene/cbarimt:latest
    ports:
      - 4114:8080
    restart: always
    environment:
      - API_KEY=1234
    volumes:
      - ./vatps:/root/.vatps
      - ./poslib:/poslib
